version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: local-search-backend:latest
    container_name: local-search-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
      - ./index:/app/index  # Mount the root-level index directory to /app/index
   
    command: ["uvicorn", "backend.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      # Add any environment variables needed
      # e.g. MODEL_PATH, etc.
      MODEL_PATH: "/app/data/models"

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: local-search-frontend:latest
    container_name: local-search-frontend
    ports:
      - "3000:3000"
    stdin_open: true  # Keep the container open
    tty: true         # Allocate a pseudo-TTY
    environment:
      # Add any frontend-specific environment variables if needed
      REACT_APP_API_URL: "http://localhost:8000"
    depends_on:
      - backend

      